name: Vcflib CI
on: [push, pull_request]
jobs:
  arch:
    name: vcflib-CI
    
    strategy:
      matrix:
          include:
              - os: ubuntu-22.04
                python-version: "3.8"
              - os: ubuntu-24.04
                python-version: "3.9"
              - os: ubuntu-24.04
                python-version: "3.10"
              - os: ubuntu-24.04
                python-version: "3.11"
              - os: ubuntu-24.04
                python-version: "3.12"
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    runs-on: ${{ matrix.os }}

    steps:
    - name: apt update
      run: sudo apt-get -o Acquire::Retries=3 update
    - name: install dependencies
      run: sudo apt-get -o Acquire::Retries=3 install -y -V
        cmake
        libhts-dev
        libtabixpp-dev
        libtabixpp0
        pybind11-dev
    - name: install libbz2-dev for 24.04
      if: matrix.os == 'ubuntu-24.04'
      run: sudo apt-get -o Acquire::Retries=3 install -y -Vlibbz2-dev # needed for ubuntu 24.04
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: install zig using wget
      run: |
        wget -q https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz
        tar xf zig-linux-x86_64-*.tar.xz
        ./zig-linux-x86_64-*/zig version
        pwd
        ls -l zig-linux-*
        echo "$(pwd)/zig-linux-x86_64-0.13.0" >> $GITHUB_PATH
        # echo "$(pwd)/zig-linux-x86_64-*" >> $GITHUB_PATH
        # echo "::add-path::./zig-linux*"
        echo GITHUB_PATH=$GITHUB_PATH
        # zig version
        # echo "{environment_variable_name}={value}" >> $GITHUB_ENV
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Configure
      run: |
        echo $(pwd)/zig-linux-x86_64-* >> $GITHUB_PATH
        echo "$(pwd)/zig-linux-x86_64-0.13.0" >> $GITHUB_PATH
        echo GITHUB_PATH=$GITHUB_PATH
        echo PATH=$PATH
        zig version
        mkdir -p build
        cd build
        # cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWFA_GITMODULE=ON ..
    - name: Compile
      run: cmake --build build/ --verbose -- -j 2
    - name: Run tests
      run: |
        cd build
        ctest --verbose
